# Paths to datasets
unsw_path: 'path/to/your/UNSW-NB15_1.csv'
cse_path: 'path/to/your/CSE-CIC-IDS2018.csv'

# Model parameters
xgboost_params:
  n_estimators: 100
  max_depth: 3
  learning_rate: 0.1

lightgbm_params:
  n_estimators: 100
  num_leaves: 31
  learning_rate: 0.1

catboost_params:
  iterations: 100
  depth: 5
  learning_rate: 0.1

dnn_params:
  input_dim: 196
  hidden_layers: [64, 32]
  dropout_rate: 0.2

lstm_params:
  timesteps: 10
  features: 196
  lstm_units: 64
